### ISSUE TITLE
Svg icons are not visible in Edge

### ISSUE THREAD

**Issue by ozguruysal** [bridgedotnet/Live#11]

**Comment by fabriciomurta** [comment]
I've noticed they were not visible also in Ext.NET forums, with IE8 (which comes with win7, I think). Some icons of those can be seen in my, daniil's and geoffrey's signature (object.net logo).

**Comment by ozguruysal** [comment]
Thanks for reporting the issue with Ext.NET forums. Since this original issue is fixed now, I'm closing it.
