### ISSUE TITLE
Live Bridge needs an "empty" (very basic) sample and an individual button to apply it

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Live#12]
Well, it is not a very big deal, but it really bothers to manually remove all that stuff from existing samples or erase entirely and type from scratch, when you just want a very basic code without any other distractions.

@ozguruysal, I am assigning to you for now to review where that individual button can be added to and how it can look in the design context.

**Comment by geoffreymcgill** [comment]
Done. See new **Simple.cs** sample. 

http://live.bridge.net/#example2
